apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust-worker
        image: fabian1207/locust
        args: ["-f", "/locust/locustfile.py", "--worker", "--master-host=locust-master"]
        env:
        - name: TARGET_HOST
          value: "http://api-service.default.svc.cluster.local"
        
